name: CI

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
    paths:
      - 'buildscripts/**'
      - 'patch/**'
      - 'patch_loader_*/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/akuhak/ps2homebrew:main
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile build
        run: |
          make clean all

      - name: Pack binaries for formal release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p release/raw_binaries
          cp patch_loader_irx/irx/ppcpatchman.irx release/ppcpatchman.irx
          cp patch_loader_ee/ee_loader.elf release/PPC-Monitor-Loader.elf
          cp patch/bin/patch.elf release/raw_binaries/patch.elf
          cp patch/bin/patch.bin release/raw_binaries/patch.bin
          cp LICENSE release/LICENSE
          cp README.md release/README.md
          make version>release/VERSION.TXT
          mv release "PPC-Monitor-$(make vershort)"
          zip -r "PPC-Monitor-$(make vershort).zip" "PPC-Monitor-$(make vershort)"/*

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PPC-Monitor
          path: |
            patch_loader_irx/irx/ppcpatchman.irx
            patch_loader_ee/ee_loader.elf
            patch/bin/patch.elf
            patch/bin/patch.bin

      - name: Create pre-release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            patch_loader_irx/irx/ppcpatchman.irx
            patch_loader_ee/ee_loader.elf

      - name: Create release with tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            patch_loader_irx/irx/ppcpatchman.irx
            patch_loader_ee/ee_loader.elf
