name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
    paths:
      - 'buildscripts/**'
      - 'patch/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/akuhak/ps2homebrew:main
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile build
        run: |
          make clean all

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PPC-Monitor
          path: |
            patch_loader_irx/irx/ppcpatchman.irx
            patch_loader_ee/ee_loader.elf
            patch/bin/patch.elf
            patch/bin/patch.bin

      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest development build"
          files: |
            patch_loader_irx/irx/ppcpatchman.irx
            patch_loader_ee/ee_loader.elf
